### ISSUE TITLE
The "self" parameter

### ISSUE THREAD

**Issue by swift502** [Zarig/DragonFF#11]
Hi (again),

I'm new to Python and I'm trying to wrap my head around the "self" keyword used as a parameter. There's many points in the code (almost all files) where my Python linter (pylint 2.3.1) in VSCode tells me there's errors because self isn't defined as the first parameter in class functions...

![image](https://user-images.githubusercontent.com/24359130/58763113-54a10b00-8557-11e9-849f-0e2571a0085c.png)

...and then when a parameter is used that isn't self...

![image](https://user-images.githubusercontent.com/24359130/58763129-6e425280-8557-11e9-861b-be80c2676384.png)

I don't want to break the conventions, so can I / should I always put self as the first parameter for class functions? Is it necessary? Does the current codebase work fine with these "errors"?

Thanks.

**Comment by Zarig** [comment]
These aren't actually errors, but rather naming conventions that pylint detects to not being followed. If you wanted, you could put a `@staticmethod` before the definition of the function. 
The reason I've not used this is because it is possible that older versions of Python might not support them. 

You can edit the `pycodestyle` file for the project to ignore the warning (I personally use `ignore = E1,E2,E3,W2,W5` and `max-line-length = 84`).

The current codebase works fine with these "errors" as I said, it is just a [naming convention suggestion](https://www.python.org/dev/peps/pep-0008/#id46) by pylint.

**Comment by swift502** [comment]
Ok so when self isn't the first parameter it's a static function?

**Comment by Zarig** [comment]
Yes, that means it's a static function. You can call it without an object.
