### ISSUE TITLE
Parappa character model won't export to .dff file

### ISSUE THREAD

**Issue by DarkUmbreon87v3rm** [Zarig/DragonFF#24]
Please developer.... make this updated

**Comment by Zarig** [comment]
You should know that simply stating that a character model won't export without providing the character model or the error you got isn't really helpful, and there isn't anything I could do with the information you've provided me.

If you get an error related to 'depsgraph', you have to download the repository as a zip file and use that instead of the one in Releases because of API changes after that version was released.

**Comment by swift502** [comment]
Parappa the rapper is in GTA? :smile:

**Comment by Zarig** [comment]
I think people from the BFBB community also use the plug-in, which is why I'm trying to implement support for that game as well. I'd imagine that DarkUmbreon87v3rm is trying to export a model for that game.

**Comment by Zarig** [comment]
From what I can tell, you are trying to export an armature without proper bone structure. Use the bone structure from the original game or else it won't work.
